### ISSUE TITLE
find value of dt

### ISSUE THREAD

**Issue by dokato** [brian-team/gsoc2016#11]
In the `add_spikemonitor` method when I'm taking data out from `StateMonitor` I wanted to update as well integration step of simulation. But when I take 'obj.clock.dt' it is always 0. Why? And if that's meant to be, how to extract that value at this point?

**Comment by mstimberg** [comment]
Ah, this is indeed confusing. With the current implementation of `LEMSDevice` the value that is returned for all state variables with `get_value` is 0, since we don't actually store the value... The time `t` and the timestep `dt` are stored as normal state variables as well, so that's why you get 0. You should get the correct value if you let it inherit from `RuntimeDevice` as I described in #6.

**Comment by dokato** [comment]
Ok, that works, thank you.
