### ISSUE TITLE
Bug in CGM example

### ISSUE THREAD

**Issue by dokato** [brian-team/gsoc2016#4]
I noticed that in `example_cgm.py` there are actually two runs which should have had separate MultiInstantiate and simulations. But I wonder how to check  what was actually changed and what to modify in that case without running a whole exporter every time again from scratch.

**Comment by mstimberg** [comment]
I think we discussed this a while ago. Short answer: don't bother with it. I think it will complicate things too much, since LEMS/NeuroML does not really have an equivalent of multiple runs. So the best solution for now would be if `LEMSDevice.network_run` simply assumes that the script only has a single `run` statement and raises a `NotImplementedError` if it is called for a second time.

**Comment by dokato** [comment]
done
